### ISSUE TITLE
SarLUG

### ISSUE THREAD

**Issue by gochankot** [boringplace/borinplace.github.io#14]
Добавить страничку о линуксовках (возможно с онлайн календарем), чтобы не писать о каждой линуксовке заранее, а только отчеты или отмены/переносы мероприятия...

**Comment by gochankot** [comment]
@NIR-Ginko за?

**Comment by NIR-Ginko** [comment]
Ну, страничка о линуксовках есть, на счёт календаря - я поддерживаю и пытаюсь найти хороший вариант. Пока не нашёл чего-то интересного.

**Comment by NIR-Ginko** [comment]
Чего-то я тут посмотрел - есть Яндекс.Календарь. Вроде работает. Я сделаю pull request после тестов, но функциональность подобной вещи подсказывает, что мы могли бы сделать календарь вида "Мероприятия Скучного Места" и упихать туда планы на все события, а не только на линуксовки.

**Comment by NIR-Ginko** [comment]
Please review: PR #15

**Comment by NIR-Ginko** [comment]
Я увидел, что изменения с календарём ушли в апстрим, но вот сам календарь, исправленный под формат мобилки, по крайней мере у меня выглядит примерно никак - читать невозможно. Может, лучше таки дополнительно потестить?

**Comment by gochankot** [comment]
Поменял, но какой-то компромис получаеться - - или немного криво или не влезает по ширине...

**Comment by NIR-Ginko** [comment]
Теперь могу разобрать содержимое, да. С шириной, конечно, беда, но более цивилизованного решения проблемы я пока предложить не могу.

Задачу закрываю.
