### ISSUE TITLE
Добавить картинку на главную и ссылку с картой и отмеченным входом

### ISSUE THREAD

**Issue by gochankot** [boringplace/borinplace.github.io#9]
Добавить
- картинку на главную 
Предлагаю выбрать вам (желательно чтобы это была панорама зала, то есть может быть проще снять ее сейчас специально для этого)
- ссылку с картой, на которой отмечен вход
можно отдельным разделом

P.s.: оба пункта, либо должны сами масштабироваться, либо нормально выглядеть и с телефона, планшета, и с маленького (10'-11') экрана (проверить вручную или сайтом специальным, например [http://quirktools.com/screenfly/](http://quirktools.com/screenfly/))

**Comment by NIR-Ginko** [comment]
У меня есть раскладной стенд по типу выставляемых около магазинов. Он не модный, а просто сварная рамка с листами оцинковки. Есть ещё масляная краска. Предлагаю разрисовать оцинковку. Стенд можно будет выставлять только при необходимости, затраты на вывеску минимальны, а если сфотографировать вход с вывеской, то будет узнаваемо.

**Comment by gochankot** [comment]
хмм @mastersin @vanaf @shubin ???

**Comment by gochankot** [comment]
Карту добавили, спасибо Игорю. Осталось фото входа

**Comment by gochankot** [comment]
@NIR-Ginko @mastersin а может не загоняться и взять эту  https://vk.com/photo-144371144_456239017?

**Comment by vanaf** [comment]
Если отделка с тех пор не улучшилась то можно её да.

Но если в самое ближайшее время планируем успеть до зимы с отделкой/ремонтом, то лучше сначала сделать а потом фоткать и выставлять на сайт

**Comment by NIR-Ginko** [comment]
Полагаю, фотка немного пересвечена странными фильтрами, но можно и её. Я тогда подумаю как и куда лучше воткнуть фотку и сделаю pull request.

**Comment by gochankot** [comment]
Задача сделана, ждем окончания review и решения (мною) конфликта merge, который я создал..
